version: '3'

services:
  # Airflow Init
  airflow-init:
    image: apache/airflow:3.0.6
    container_name: nasa_airflow_init
    entrypoint: /bin/bash
    command: >
      -c "
      pip install apache-airflow-providers-snowflake kafka-python snowflake-connector-python dbt-core dbt-snowflake psycopg2-binary &&
      airflow db migrate &&
      airflow users create -r Admin -u admin -e admin@example.com -f admin -l user -p admin &&
      airflow connections add 'postgres_default'
        --conn-type 'postgres'
        --conn-login 'postgres'
        --conn-password '1234'
        --conn-host 'host.docker.internal'
        --conn-port '5432'
        --conn-schema 'airflow'
      "
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:1234@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./Airflow/dags:/opt/airflow/dags
      - ./Airflow/logs:/opt/airflow/logs
      - ./Airflow/plugins:/opt/airflow/plugins
      - ./DBT:/opt/airflow/dbt
      - ./ML:/opt/airflow/project/ML
      - ./Kafka:/opt/airflow/project/Kafka
    networks:
      - iot-network

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:3.0.6
    container_name: nasa_airflow_webserver
    depends_on:
      - airflow-init
    command: api-server
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:1234@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./Airflow/dags:/opt/airflow/dags
      - ./Airflow/logs:/opt/airflow/logs
      - ./Airflow/plugins:/opt/airflow/plugins
      - ./DBT:/opt/airflow/dbt
      - ./ML:/opt/airflow/project/ML
      - ./Kafka:/opt/airflow/project/Kafka
    networks:
      - iot-network
    restart: unless-stopped

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:3.0.6
    container_name: nasa_airflow_scheduler
    depends_on:
      - airflow-init
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:1234@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./Airflow/dags:/opt/airflow/dags
      - ./Airflow/logs:/opt/airflow/logs
      - ./Airflow/plugins:/opt/airflow/plugins
      - ./DBT:/opt/airflow/dbt
      - ./ML:/opt/airflow/project/ML
      - ./Kafka:/opt/airflow/project/Kafka
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge
