WITH neo_proximity AS (
    SELECT *
    FROM {{ ref('fact_iss_neo_proximity') }}
),

eonet_events AS (
    SELECT *
    FROM {{ ref('stg_eonet_events') }}
)

SELECT
    DATE_TRUNC('day', n.EVENT_TIME) as EVENT_DATE,
    COUNT(DISTINCT CASE WHEN n.IS_POTENTIALLY_HAZARDOUS THEN n.NEO_ID END) as HAZARDOUS_NEO_COUNT,
    AVG(n.MISS_DISTANCE_KM) as AVG_MISS_DISTANCE_KM,
    MAX(n.VELOCITY_KPH) as MAX_NEO_VELOCITY_KPH,
    COUNT(DISTINCT e.EVENT_ID) as EARTH_EVENT_COUNT,
    COUNT(DISTINCT CASE WHEN e.CLOSED THEN e.EVENT_ID END) as CLOSED_EVENT_COUNT,
    MIN(n.INGESTED_AT) as FIRST_INGESTION,
    MAX(n.INGESTED_AT) as LAST_INGESTION
FROM neo_proximity n
LEFT JOIN eonet_events e
    ON DATE_TRUNC('day', n.EVENT_TIME) = DATE_TRUNC('day', e.EVENT_TIME)
GROUP BY 1
ORDER BY 1 DESC
