-- Create tables for NASA data

-- ISS Events table
CREATE TABLE IF NOT EXISTS ISS_EVENTS (
    EVENT_TIME TIMESTAMP,
    DATA VARIANT,  
    PRIMARY KEY (EVENT_TIME)
);

-- EONET Events table
CREATE TABLE IF NOT EXISTS EONET_EVENTS (
    EVENT_TIME TIMESTAMP,
    DATA VARIANT,
    PRIMARY KEY (EVENT_TIME)
);

-- NEO Events table
CREATE TABLE IF NOT EXISTS NEO_EVENTS (
    EVENT_TIME TIMESTAMP,
    DATA VARIANT,
    PRIMARY KEY (EVENT_TIME)
);
